services:
  game-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
      - ./public:/app/public
      - ./replays:/app/replays
    environment:
      DEBUG: "false"
      REPLAY_HISTORY: "10"
    restart: unless-stopped

